### ISSUE TITLE
MERFISH data

### ISSUE THREAD

**Issue by AminaLEM** [saezlab/DOT#1]
Hello, 

I appreciate DOT, the results are interesting.
I have a question about MERFISH dataset you used, you mentioned in your paper that there are 75 samples but I found only 64 slices in the processed data which are shown here https://download.brainimagelibrary.org/cf/1c/cf1c1a431ef8d021/processed_data/cell_labels.csv 

Could you clarify this?

Thanks!
Amina

**Comment by arezourahimi** [comment]
The dataset contains some unnamed instances which together with the 64 named instances add up to a total of 75. You may ignore the unnamed instances if you wish.
