### ISSUE TITLE
Gene Expression Inference

### ISSUE THREAD

**Issue by AminaLEM** [saezlab/DOT#2]
Hello, 

Could you kindly provide more information on how to infer missing genes within the spatial data? Where is the transport Matrix?

Thanks,
Amina

**Comment by arezourahimi** [comment]
Current you can extract the optimal transport matrix from dot@solution and dot@weights. The former contains the complete solution with respect to the subclusters, while the latter contains the aggregated solution based on the original clusters. The full solution containing the subcluster memberships will be available in the next update of the package.
