### ISSUE TITLE
Issues in setup.ref() with Seurat v5

### ISSUE THREAD

**Issue by robinfallegger** [saezlab/DOT#4]
When DOT does highly variable gene selection for `setup.ref()` it throws the following error:
```
Error in order(vg$vst.variance.standardized, decreasing = TRUE) : 
  argument 1 is not a vector
Calls: setup.ref -> order
```

This is due to the fact that they have refactored the output of FindVariableFeatures and how it is stored in the Seurat object.

I have fixed it for my scripts by doing:
```
if (seurat_obj %>% nrow() > max_genes){
    vg <- Seurat::FindVariableFeatures(seurat_obj, selection.method = "vst") %>% HVFInfo()
    vg <- rownames(vg)[order(vg$variance.standardized,  decreasing = TRUE)[1:max_genes]]
    seurat_obj <- seurat_obj[vg, ]
}
```
before running `setup.ref()`

**Comment by arezourahimi** [comment]
Thanks, Robin. Yes, I recently noticed that. It's fixed now.
