### ISSUE TITLE
AnnData as input to setup.srt()

### ISSUE THREAD

**Issue by EST09** [saezlab/DOT#5]
Hi,

Thank you for this package. It looks great and I'm really looking forward to using it!

I'm struggling a little with setting up my srt object with an anndata input. I load the anndata from a h5ad file
<img width="750" alt="Screenshot 2024-06-20 at 11 35 52" src="https://github.com/saezlab/DOT/assets/25770709/0e6d8742-afd1-4842-b63d-eb31421bd097">

and then try

dot.srt <- setup.srt(srt_data=ex_anndata$X, srt_coords=ex_anndata$obsm["spatial"])
My ex_anndata$X seems to be a matrix

<img width="707" alt="Screenshot 2024-06-20 at 11 36 34" src="https://github.com/saezlab/DOT/assets/25770709/d0511cd5-bc7f-44e7-bce1-5c023b0b2358">

and my coordinates from ex_anndata$obsm["spatial"] are the same length as my matrix

<img width="341" alt="Screenshot 2024-06-20 at 11 37 08" src="https://github.com/saezlab/DOT/assets/25770709/3ef65d1c-ae25-4956-af18-dbdadb0f5288">

<img width="252" alt="Screenshot 2024-06-20 at 11 37 36" src="https://github.com/saezlab/DOT/assets/25770709/57e89ad6-500c-4a58-9177-af4b0130ac06">

Please could I check if there's something I'm missing?

I can load from a standard xenium output using the Seurat LoadXenium() function but I've changed the segmentation and saved to a xenium experiment format with sopa, and then Seurat is having trouble with the cell_feature_matrix.zarr.zip files which is why I've gone the h5ad anndata route.

Thank you,

Best wishes,
Emily

**Comment by EST09** [comment]
sorry I'd supplied srt_data it as spot x gene - transposed it now. Thank you!

**Comment by elinaiselina** [comment]
could I ask what method did you used to read the anndata to R?

**Comment by EST09** [comment]
Hi,

yep I remember it being fiddly - I ended up using the combo of python and r running in r with reticulate

```
library(reticulate)
use_condaenv("r-reticulate")
ad <- import("anndata", convert = FALSE)

library("anndata")

for (i in files){
  print(i)
  file_path = paste0(base_path, i)
  xen_ad <- read_h5ad(file_path)
  data <- CreateSeuratObject(counts = t(as.matrix(xen_ad$X)), meta.data = xen_ad$obs)
  colnames(data) <- data$cell_id
  rownames(data) <- xen_ad$var_names
  saveRDS(data, sub("h5ad", "rds", file_path))
}
```

then merge your rds files

BW, 
Emily
